from dao.singletonDao import Singleton


class Database:
    dao = Singleton()
    mycursor = dao.cursor()

    mycursor.execute("""CREATE DATABASE BOT;
USE BOT;

CREATE TABLE USER(
ID INT PRIMARY KEY AUTO_INCREMENT,
TEL_NUMBER VARCHAR(60) NOT NULL,
EMAIL VARCHAR(255) NOT NULL,
AUTHENTICATION_KEY VARCHAR(255) NOT NULL,
USER_NAME VARCHAR(30) NOT NULL);

CREATE TABLE COMMANDS_USER(
ID INT PRIMARY KEY AUTO_INCREMENT,
ID_COMMAND INT NOT NULL,
ID_USER INT NOT NULL,
TYPEOF VARCHAR(30),
PROMPT VARCHAR(255),
OCCASION DATETIME,
FOREIGN KEY(ID_USER) REFERENCES USER(ID),
FOREIGN KEY(ID_COMMAND) REFERENCES COMMANDS(ID));

CREATE TABLE COMMANDS(
ID INT PRIMARY KEY AUTO_INCREMENT,
VALUE INT NOT NULL,
STATUS BOOLEAN);

CREATE TABLE BLACKLIST(
ID_USER INT,
ID_COMMAND INT,
DESCRIPTION VARCHAR(255),
FOREIGN KEY(ID_USER) REFERENCES USER(ID),
FOREIGN KEY(ID_COMMAND) REFERENCES COMMANDS(ID));

CREATE TABLE USER_MANAGER(
ID INT PRIMARY KEY AUTO_INCREMENT,
LOGIN VARCHAR(255),
PASSWORD VARCHAR(255),
EMAIL VARCHAR(255));
""")
